### ISSUE TITLE
Spec incorrectly claims that strings are treated as sequences in compound assignment

### ISSUE THREAD

**Issue by haberman** [bazelbuild/starlark#281]
The spec contains this example in [assignments](https://github.com/bazelbuild/starlark/blob/master/spec.md#assignments):

```
[(a, b), (c, d)] = ("ab", "cd")
```

However, this statement is rejected by both Bazel and https://github.com/google/starlark-go

Bazel:

```
ERROR: Traceback (most recent call last):
	File "/Users/haberman/bazel_workspace/test.bzl", line 27, column 8, in <toplevel>
		print(f())
	File "/Users/haberman/bazel_workspace/test.bzl", line 24, column 20, in f
		[(a, b), (c, d)] = ("ab", "cd")
Error: got 'string' in sequence assignment (want 2-element sequence)
```

starlark-go:

```
Traceback (most recent call last):
  test.bzl:27:8: in <toplevel>
  test.bzl:24:20: in f
Error: got string in sequence assignment
```

**Comment by laurentlb** [comment]
Thanks, the example looks wrong to me, it should be removed.

**Comment by joydeep049** [comment]
Hello!
I would like to contribute.
Can anyone tell me how to get started?
